### ISSUE TITLE
TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by zaoqi** [quadramadery/js2py#5]
```
> new (require('js2py').JS2Py)().convert(require('fs').readFileSync('tmp-pass2.js','utf8'))
```
```
Thrown:
TypeError: Cannot read property 'type' of null
    at ToPyCodeVisitor.leaveForStatement (.../ToPyCodeVisitor.js:167:18)
    at Function.traverse (.../Traverse.js:28:50)
    at ast.map.elem (.../Traverse.js:9:39)
    at Array.map (<anonymous>)
    at Function.traverse (.../Traverse.js:9:18)
    at Function.traverse (.../Traverse.js:23:27)
    at Function.traverse (.../Traverse.js:23:27)
    at ast.map.elem (.../Traverse.js:9:39)
    at Array.map (<anonymous>)
    at Function.traverse (.../Traverse.js:9:18)
```
https://paste.debian.net/1094250/

**Comment by zaoqi** [comment]
it's
```js
function _flatten_18 (_closure, k, v) {
    var i = 0;
    for (; i < _closure.args_pat_vars.length; i++) {
        if (_closure._closure_0.equal_p(_closure.args_pat_vars[i], k)) {
            return;
        }
    }
    _closure.env_vars.push(k);
};
```
